### ISSUE TITLE
plexapi.exceptions.BadRequest: ekey was not provided

### ISSUE THREAD

**Issue by ellisonpatterson** [RemiRigal/Plex-Auto-Languages#102]
Started getting this error recently. Using the config.yaml and it is parsing it correctly. I have specified the plex server and token, and do not have the docker environment variables for those specified with the plexautolanguages container.

```
2024-08-06 10:50:15,222 [ERROR] Unable to process playing
Traceback (most recent call last):
  File "/app/plex_auto_languages/plex_alert_handler.py", line 66, in _process_alerts
    alert.process(self._plex)
  File "/app/plex_auto_languages/alerts/playing.py", line 55, in process
    if plex.should_ignore_show(item.show()):
  File "/usr/local/lib/python3.8/site-packages/plexapi/video.py", line 990, in show
    return self.fetchItem(self.grandparentKey)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 307, in fetchItem
    return self.fetchItems(ekey, cls, **kwargs)[0]
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 235, in fetchItems
    raise BadRequest('ekey was not provided')
plexapi.exceptions.BadRequest: ekey was not provided
```

**Comment by flip1900** [comment]
i have the same issue, any ways to fix it?
