### ISSUE TITLE
PAL keeps crashing after a while

### ISSUE THREAD

**Issue by s0len** [RemiRigal/Plex-Auto-Languages#107]
Not sure why this is happening but I need to restart it manually to solve it each time. 

Here's the log output:
2024-11-20 02:00:37,419 [INFO] Language update: Episode: What We Do in the Shadows (S06E07) | Status: Updated episode | Updated for all users
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='plex.media.svc.cluster.local', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 143, in <module>
    plex_auto_languages.start()
  File "/app/main.py", line 91, in start
    if count % 60 == 0 and not self.plex.is_alive:
                               ^^^^^^^^^^^^^^^^^^
  File "/app/plex_auto_languages/plex_server.py", line 122, in is_alive
    return self.connected and self._alert_listener is not None and self._alert_listener.is_alive()
           ^^^^^^^^^^^^^^
  File "/app/plex_auto_languages/plex_server.py", line 39, in connected
    _ = self._plex.library.sections()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/library.py", line 75, in sections
    self._loadSections()
  File "/usr/local/lib/python3.12/site-packages/plexapi/library.py", line 62, in _loadSections
    for elem in self._server.query(key):
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/server.py", line 760, in query
    response = method(url, headers=headers, params=params, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='plex.media.svc.cluster.local', port=32400): Read timed out. (read timeout=30)
ERROR:plexapi:AlertListener Error: Connection to remote host was lost.
2024-11-20 05:10:20,449 [WARNING] The Plex server closed the websocket connection
ERROR:websocket:Connection to remote host was lost. - goodbye

**Comment by s0len** [comment]
@JourneyOver i am running your image of  PAL

**Comment by JourneyOver** [comment]
> @JourneyOver i am running your image of PAL

As in the error above is coming from my version or that you are now running my version due to the above error?

I've not seen an actual full on crash at all myself since forking and updating things, couple times there will be an big error message from me shutting down plex temporarily for one reason or another or a small connectionerror message coming up because my internet is crap sometimes but it normally just does a retry and starts working.

I do see that you are running it through the host of `plex.media.svc.cluster.local`, have you tried running through just normal IP by chance to see if it ever ran into the crash? could be that there is something wrong with your hosting setup or something.

I'll take a closer look at things when I get a chance, but if I can't reproduce it any then I'm not sure if I'll be able to really fix your issue short of maybe seeing about upping the value of the read timeout some more or looking into adding a retry into the code for if PAL hits a `read timed out` message but even then these would just be temporary measures that may not even work in the end.

**Comment by BelminH** [comment]
+1 on this, having the same issue, running the latest docker image.

**Comment by kratoz29** [comment]
> > [@JourneyOver](https://github.com/JourneyOver) i am running your image of PAL
> 
> As in the error above is coming from my version or that you are now running my version due to the above error?
> 
> I've not seen an actual full on crash at all myself since forking and updating things, couple times there will be an big error message from me shutting down plex temporarily for one reason or another or a small connectionerror message coming up because my internet is crap sometimes but it normally just does a retry and starts working.
> 
> I do see that you are running it through the host of `plex.media.svc.cluster.local`, have you tried running through just normal IP by chance to see if it ever ran into the crash? could be that there is something wrong with your hosting setup or something.
> 
> I'll take a closer look at things when I get a chance, but if I can't reproduce it any then I'm not sure if I'll be able to really fix your issue short of maybe trying to add a retry into the code for if PAL hits a `read timed out` message but even then these would just be temporary measures that may not even work in the end.

Hi, Sorry to bother you, I did not want to create another thread as this project is no longer mantained (and I don't think I can crate threads in the docker hub site...

Anyway, I haven't spot if I always get issues with PAL because of Plex time outs (most likely that is the case), for example this is a recent one (I turned off Plex on purpose for testing):

```
2025-02-13 19:18:20,572 [WARNING] Connection error: Unable to connect to Plex server. Retrying... (Attempt 300/300)

2025-02-13 19:18:25,573 [ERROR] Failed to connect to Plex server after 300 attempts.

2025-02-13 19:18:25,574 [ERROR] Unable to find the user associated with the provided Plex Token

2025-02-13 19:18:25,575 [ERROR] Error during initialization: 

Traceback (most recent call last):

  File "/app/main.py", line 215, in <module>

    plex_auto_languages.start()

    ~~~~~~~~~~~~~~~~~~~~~~~~~^^

  File "/app/main.py", line 135, in start

    self.init()

    ~~~~~~~~~^^

  File "/app/main.py", line 66, in init

    self.plex = PlexServer(

                ~~~~~~~~~~^

        self.config.get("plex.url"),

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    ...<2 lines>...

        self.config

        ^^^^^^^^^^^

    )

    ^

  File "/app/plex_auto_languages/plex_server.py", line 113, in __init__

    raise UserNotFound

plex_auto_languages.exceptions.UserNotFound
```

This is running in your image of course...

Anyway, when that happens the container is labeled as "unhealthy" (despite the compose not having healtchecks of any sort) can you tell me if it is possible that when this scenario occurs the container image reboots automatically? (rebooting the container usually never fails for me).

As of now I could get this working with a script created from the task scheduler of my Synology NAS, it seems to be working fine as of now, but I had the impression one could get this done from the container itself.

Thanks in advance!
