### ISSUE TITLE
无法连接服务

### ISSUE THREAD

**Issue by curryhendry** [RemiRigal/Plex-Auto-Languages#108]
您好，我是QNAP通过qpkg安装的plex，并在docker部署的plex-auto-languages。

目前报错，无法连接到plex服务器，辛苦帮忙看下是为什么。我通过GPT帮助尝试配置了代理、配置了DNS都不能正常使用。辛苦帮忙看下是什么问题。感谢

```
2024-11-28 12:05:21,045 [INFO] Received SIGINT or SIGTERM, stopping gracefully
2024-11-28 12:05:40,449 [INFO] Setting value of parameter PLEX_URL from environment variable
2024-11-28 12:05:40,451 [INFO] Setting value of parameter PLEX_TOKEN from environment variable
2024-11-28 12:05:40,454 [INFO] The provided configuration has been successfully validated
2024-11-28 12:05:40,457 [INFO] Starting scheduler
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0xffffacdae430>: Failed to resolve 'plex.tv' ([Errno -3] Try again)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='plex.tv', port=443): Max retries exceeded with url: /api/v2/user (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffffacdae430>: Failed to resolve 'plex.tv' ([Errno -3] Try again)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 118, in <module>
    plex_auto_languages.start()
  File "main.py", line 68, in start
    self.init()
  File "main.py", line 45, in init
    self.plex = PlexServer(self.config.get("plex.url"), self.config.get("plex.token"), self.notifier, self.config)
  File "/app/plex_auto_languages/plex_server.py", line 103, in __init__
    self._user = self._get_logged_user()
  File "/app/plex_auto_languages/plex_server.py", line 142, in _get_logged_user
    plex_username = self._plex.myPlexAccount().username
  File "/usr/local/lib/python3.8/site-packages/plexapi/server.py", line 317, in myPlexAccount
    self._myPlexAccount = MyPlexAccount(token=self._token, session=self._session)
  File "/usr/local/lib/python3.8/site-packages/plexapi/myplex.py", line 122, in __init__
    data, initpath = self._signin(username, password, code, remember, timeout)
  File "/usr/local/lib/python3.8/site-packages/plexapi/myplex.py", line 127, in _signin
    return self.query(self.key), self.key
  File "/usr/local/lib/python3.8/site-packages/plexapi/myplex.py", line 229, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='plex.tv', port=443): Max retries exceeded with url: /api/v2/user (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffffacdae430>: Failed to resolve 'plex.tv' ([Errno -3] Try again)"))
```

**Comment by tblaudez** [comment]
It looks like you are trying to connect to **https://plex.tv** (port 443).  
I don't know that it works to connect to Plex's official servers (plex.tv), you should try to connect to your own *Plex Media Server* server (the one you are running on your QNAP).  
For instance, if your Plex server is running at IP address **192.168.1.30**, you should have _Plex-Auto-Languages_ connect to `http://192.168.1.30:32400`

---
看起来您正在尝试连接到 **https://plex.tv** (端口 443)。
我不知道它是否可以连接到 Plex 的官方服务器（plex.tv），您应该尝试连接到您自己的 *Plex Media Server* 服务器（您在 QNAP 上运行的服务器）。
例如，如果您的 Plex 服务器的 IP 地址为 **192.168.1.30**，则应让 _Plex-Auto-Languages_ 连接到 `http://192.168.1.30:32400`
