### ISSUE TITLE
Latest update broke for me

### ISSUE THREAD

**Issue by BEisem** [RemiRigal/Plex-Auto-Languages#25]
I just updated to the latest build posted. Now when I try to run, it crashes immediately with the following output:

```
Traceback (most recent call last):
  File "main.py", line 297, in <module>
    plex_auto_languages = PlexAutoLanguages(args.config_file)
  File "main.py", line 25, in __init__
    self.healthcheck_server = HealthcheckServer("Plex-Auto-Languages", self.is_ready, self.is_healthy)
  File "/app/utils/healthcheck.py", line 20, in __init__
    self._server = make_server("0.0.0.0", 80, self._app)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/serving.py", line 849, in make_server
    return BaseWSGIServer(
  File "/usr/local/lib/python3.8/site-packages/werkzeug/serving.py", line 693, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use
```

**Comment by RemiRigal** [comment]
The issue was that the health-check server was running on port `80` (set this with Docker in mind), which requires elevated privileges. This setting has been updated by #27, the server will now run on port `9880` from version `v1.0.12`. Please update and let me know if everything is back to normal.

Thank you for opening an issue !

**Comment by BEisem** [comment]
That fixed it. Thank you!
