### ISSUE TITLE
Unable to find elem: cls=Season

### ISSUE THREAD

**Issue by saviktkr** [RemiRigal/Plex-Auto-Languages#61]
My PAL docker seems to be stuck during caching:

[INFO]` Scanning all episodes from the Plex library, this action should only take a few seconds but can take several minutes for larger libraries
[DEBUG] [Cache] Refreshing library cache
Traceback (most recent call last):
  File "main.py", line 118, in <module>
    plex_auto_languages.start()
  File "main.py", line 68, in start
    self.init()
  File "main.py", line 45, in init
    self.plex = PlexServer(self.config.get("plex.url"), self.config.get("plex.token"), self.notifier, self.config)
  File "/app/plex_auto_languages/plex_server.py", line 110, in __init__
    self.cache = PlexServerCache(self)
  File "/app/plex_auto_languages/plex_server_cache.py", line 44, in __init__
    self.refresh_library_cache()
  File "/app/plex_auto_languages/plex_server_cache.py", line 68, in refresh_library_cache
    for episode in self._plex.episodes():
  File "/app/plex_auto_languages/plex_server.py", line 62, in episodes
    return self._plex.library.all(libtype="episode", container_size=1024)
  File "/usr/local/lib/python3.8/site-packages/plexapi/library.py", line 114, in all
    for item in section.all(**kwargs):
  File "/usr/local/lib/python3.8/site-packages/plexapi/library.py", line 672, in all
    return self.search(libtype=libtype, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/plexapi/library.py", line 1519, in search
    return self._search(key, maxresults, container_start, container_size, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/plexapi/library.py", line 1531, in _search
    subresults = self.fetchItems(key, container_start=container_start,
  File "/usr/local/lib/python3.8/site-packages/plexapi/library.py", line 451, in fetchItems
    items = self.findItems(data, cls, ekey, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 312, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 101, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 93, in _buildItem
    return ecls(self._server, elem, initpath)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 56, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.8/site-packages/plexapi/video.py", line 854, in _loadData
    if self.skipParent and not self.parentRatingKey:
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 502, in __getattribute__
    self._reload(_overwriteNone=False)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 378, in _reload
    self._loadData(data[0])
  File "/usr/local/lib/python3.8/site-packages/plexapi/video.py", line 860, in _loadData
    self.parentRatingKey = self.show().season(season=self.parentIndex).ratingKey
  File "/usr/local/lib/python3.8/site-packages/plexapi/video.py", line 555, in season
    return self.fetchItem(key, Season, index=index)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 182, in fetchItem
    raise NotFound(f'Unable to find elem: cls={clsname}, attrs={kwargs}')
plexapi.exceptions.NotFound: Unable to find elem: cls=Season, attrs={'index': 38}

**Comment by RemiRigal** [comment]
Hi @saviktkr, thank you for reporting this issue. Sorry for the delayed response, you reported this a long time ago.

Are you still experiencing this issue ? If yes, could you confirm that your Plex server contains at least one TV Show library ?

**Comment by saviktkr** [comment]
I am still experiencing this issue and have never been able to get PAL to function properly. My Plex server currently contains 11 TV show libraries.
