### ISSUE TITLE
[Error 104]  Repeating Exactly Every 2 Hours

### ISSUE THREAD

**Issue by zluckytraveler** [RemiRigal/Plex-Auto-Languages#86]
I have multiple instances of PAL running via docker containers on MacOS using the latest stable release, for multiple Plex servers that I have, and they all have the exact same errors happening over and over again **exactly every 2 hours**.

```
2023-08-09 16:19:43,793 [WARNING] ReadTimeout while processing playing alert, retrying (attempt 1)...
2023-08-09 16:19:43,979 [ERROR] Alert listener had an unexpected error
2023-08-09 16:19:43,980 [ERROR] [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 428, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 99, in read
    if not read_callback():
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 437, in read
    op_code, frame = self.sock.recv_data_frame(True)
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.8/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.8/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.8/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.8/site-packages/websocket/_socket.py", line 108, in recv
    bytes_ = _recv()
  File "/usr/local/lib/python3.8/site-packages/websocket/_socket.py", line 87, in _recv
    return sock.recv(bufsize)
  File "/usr/local/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by RemiRigal** [comment]
Hi @zluckytraveler, could you provide more information about your networking setup ? Do you have Plex running via docker containers as well ?
Could you also give me the logs that you get during startup ?
Also, does it work as expected before the 2 hours mark ?

**Comment by zluckytraveler** [comment]
@RemiRigal 

The server that PAL is running on is pretty basic network setup, there is no reverse proxies or anything like that. I have not configured any network settings for this machine as it is on a rented Mac Mini from https://macminvault.com, and only have docker desktop running on it, where I host my applications which run 24/7.

Yes all of the Plex servers are running via docker containers on Hetzner i9 9900k servers which is a different machine than from where PAL is running from.

Yes it works as expected. It works for 2 hours, errors out, then works again, and continues to repeat this process every 2 hours.

Here is logs of startup and showing it is repeating for the first occurrence. All of the containers are like this.
```
2023-08-08 22:39:01,194 [INFO] Parsing config file '/config/config.yaml'
2023-08-08 22:39:01,199 [INFO] Setting value of parameter PLEX_URL from environment variable
2023-08-08 22:39:01,199 [INFO] Setting value of parameter PLEX_TOKEN from environment variable
2023-08-08 22:39:01,199 [INFO] The provided configuration has been successfully validated
2023-08-08 22:39:02,657 [INFO] Successfully connected as user 'ZLucky1' (id: 1)
2023-08-08 22:39:03,230 [INFO] Starting alert listener
2023-08-08 22:40:13,062 [INFO] Language update: Show: Futurama | User: apex videos | Audio: English (EAC3 Stereo) | Subtitles: None | Updated episodes: 8/127 (S01E01 - S08E03)
2023-08-08 22:40:45,955 [INFO] Language update: Show: It's Always Sunny in Philadelphia | User: squizzy99 | Audio: English (AC3 Stereo) | Subtitles: None | Updated episodes: 15/169 (S01E01 - S16E08)
2023-08-08 22:41:53,921 [INFO] Language update: Show: Better Call Saul | User: TooFurious | Audio: English (DTS-HD MA 5.1) | Subtitles: None | Updated episodes: 19/65 (S00E11 - S06E13)
2023-08-08 22:45:08,642 [INFO] Language update: Show: It's Always Sunny in Philadelphia | User: dall292 | Audio: English (AC3 Stereo) | Subtitles: None | Updated episodes: 15/169 (S01E01 - S16E08)
2023-08-08 23:04:35,804 [INFO] Language update: Show: It's Always Sunny in Philadelphia | User: dall292 | Audio: English (DTS-HD MA 5.1) | Subtitles: None | Updated episodes: 15/169 (S01E01 - S16E08)
2023-08-08 23:11:59,134 [INFO] [Status] Processing newly added episode 'Roadkill' (S12E08)
2023-08-08 23:16:27,691 [INFO] [Status] Processing newly added episode 'EastEnders' (S39E128)
2023-08-09 00:20:21,651 [ERROR] Alert listener had an unexpected error
2023-08-09 00:20:21,651 [ERROR] [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 428, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 99, in read
    if not read_callback():
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 437, in read
    op_code, frame = self.sock.recv_data_frame(True)
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 406, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 445, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.8/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.8/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.8/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.8/site-packages/websocket/_core.py", line 529, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.8/site-packages/websocket/_socket.py", line 108, in recv
    bytes_ = _recv()
  File "/usr/local/lib/python3.8/site-packages/websocket/_socket.py", line 87, in _recv
    return sock.recv(bufsize)
  File "/usr/local/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
ConnectionResetError: [Errno 104] Connection reset by peer
2023-08-09 00:20:23,549 [WARNING] ReadTimeout while processing playing alert, retrying (attempt 1)...
2023-08-09 00:20:25,550 [INFO] Trying to restore the connection to the Plex server...
2023-08-09 00:20:26,714 [INFO] Successfully connected as user 'ZLucky1' (id: 1)
2023-08-09 00:20:28,307 [INFO] Starting alert listener
2023-08-09 00:25:39,323 [INFO] [Timeline] Processing newly added episode 'Doubling Down with the Derricos' (S04E10)
2023-08-09 01:08:07,430 [INFO] Language update: Show: Futurama | User: ctaumoe | Audio: English (EAC3 Stereo) | Subtitles: None | Updated episodes: 8/127 (S01E01 - S08E03)
2023-08-09 01:44:21,592 [INFO] Language update: Show: It's Always Sunny in Philadelphia | User: squizzy99 | Audio: English (DTS-HD MA 5.1) | Subtitles: None | Updated episodes: 15/169 (S01E01 - S16E08)
2023-08-09 01:51:05,171 [INFO] [Status] Processing newly added episode 'Justified: City Primeval' (S01E05)
2023-08-09 02:20:17,918 [ERROR] Alert listener had an unexpected error
2023-08-09 02:20:17,918 [ERROR] [Errno 104] Connection reset by peer
```

**Comment by zluckytraveler** [comment]
@RemiRigal It's some time Ince I have heard from you. Can you help me out with this?

**Comment by eandrade92630** [comment]
@zluckytraveler you sure posted a lot of unnecessary information and never answered the question properly

**Comment by zluckytraveler** [comment]
@eandrade92630 what’s your issue? I answered every question to the best of my abilities without any specifications, as requested. 

If you don’t have anything nice or productive to say you should keep it to yourself.
